# Generated by Django 2.1.7 on 2019-03-06 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Class_Data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Data_Name', models.CharField(max_length=200)),
                ('Data_Date', models.DateTimeField(verbose_name='Date_Uploaded')),
            ],
        ),
    ]
