# Generated by Django 2.1.7 on 2019-03-08 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DA_Simulation', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Class_Spectrum_Model',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Data_Name', models.CharField(max_length=200)),
                ('Data_Date', models.DateTimeField(verbose_name='Date_Operation')),
            ],
        ),
        migrations.AddField(
            model_name='class_data',
            name='Data_Col_1',
            field=models.CharField(default='00000000', max_length=300),
        ),
        migrations.AddField(
            model_name='class_data',
            name='Data_Col_2',
            field=models.CharField(default='00000000', max_length=300),
        ),
        migrations.AlterField(
            model_name='class_data',
            name='Data_Date',
            field=models.DateTimeField(default='00000000', verbose_name='Date_Uploaded'),
        ),
        migrations.AlterField(
            model_name='class_data',
            name='Data_Name',
            field=models.CharField(default='00000000', max_length=200),
        ),
    ]
